# Generated by Django 5.1.7 on 2026-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_resume_created_at_alter_resume_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
